---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elastic
  - src: git@github.com:Dmitriy-rzn/filebeat-role.git
    scm: git
    name: filebeat
  - src: git@github.com:Dmitriy-rzn/kibana-role.git
    scm: git
    name: kibana
