apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
      - name: web
        image: {{ .Values.web_deployment.image.repository }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: webapp
          protocol: TCP