apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.app_nginx_service.nodeport }}